const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, 'indexecom1.html');
let html = fs.readFileSync(filePath, 'utf8');

// 1. Replace section header and subtitle text for How We Work
const oldTitle = '<h2 class="section-title gradient-heading">Our Backend Development Workflow Process</h2>';
const newTitle = '<h2 class="section-title gradient-heading">Our eCommerce Website Development Workflow Process</h2>';

const oldSub = '<div class="hww-sub-top">Our backend development workflow follows a structured approach covering requirements, architecture, development, testing, deployment, and support to deliver secure, scalable, and dependable systems.</div>';
const newSub = '<div class="hww-sub-top">Our eCommerce development workflow follows a structured, transparent process covering discovery, planning, design, development, testing, launch, and ongoing optimization for dependable online growth and performance.</div>';

if (html.includes(oldTitle)) html = html.replace(oldTitle, newTitle);
if (html.includes(oldSub)) html = html.replace(oldSub, newSub);

// Also check Section 3 title if it says Backend
const oldSec3Title = '<h2 class="section-title gradient-heading">Our Backend Development Services</h2>';
const newSec3Title = '<h2 class="section-title gradient-heading">Our eCommerce Website Development Services</h2>';
if (html.includes(oldSec3Title)) html = html.replace(oldSec3Title, newSec3Title);

// 2. Replace JS steps array
const newStepsCode = `  const steps=[
    {num:'01',label:'Commerce Requirements & Experience Analysis',title:'Commerce Requirements & Experience Analysis',desc:'We begin by understanding your products, customers, markets, sales model, operational workflows, and technical expectations. This stage defines the store structure, customer journey, essential features, integrations, platform direction, and delivery priorities.',subs:[{title:'Business and Market Analysis',desc:'We analyse products, customers, competitors, markets, and commercial goals.',icon:'<path d="M3 3h18v18H3zM3 9h18M9 21V9"/>'},{title:'Requirement Gathering',desc:'We document features, users, workflows, integrations, and reporting needs.',icon:'<path d="M9 11l3 3L22 4"/><path d="M21 12v7a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11"/>'},{title:'Customer Journey Planning',desc:'We plan discovery, product, cart, checkout, and account experiences.',icon:'<rect x="3" y="3" width="18" height="18" rx="2"/><path d="M3 9h18M9 21V9"/>'},{title:'Platform and Technology Selection',desc:'We select suitable platforms, frameworks, databases, hosting, and integrations.',icon:'<path d="M12 2l3.09 6.26L22 9.27l-5 4.87L18.18 21 12 17.77 5.82 21 7 14.14l-5-4.87 6.91-1.01L12 2z"/>'}],deliverables:['Approved commerce requirements document','Customer journeys and store structure','Feature and integration plan','Platform recommendation and project roadmap'],illus:'<img src="Workflow Image/custom-web-development-requirements-design-analysis.webp" alt="Commerce Requirements & Experience Analysis" style="width:100%;height:auto;display:block;border:none;outline:none;border-radius:0;box-shadow:none;mix-blend-mode:multiply;filter:contrast(1.05) saturate(1.1);background:transparent;">' },
    {num:'02',label:'Platform Planning & Technical Setup',title:'Platform Planning & Technical Setup',desc:'After requirements are approved, we establish the commerce architecture, environments, database approach, development standards, milestones, and collaboration process. This creates an organised foundation for secure development, integration, testing, and controlled delivery.',subs:[{title:'Commerce Architecture',desc:'We define storefront, backend, database, API, and service architecture.',icon:'<rect x="2" y="2" width="20" height="8" rx="2"/><rect x="2" y="14" width="20" height="8" rx="2"/><line x1="6" y1="6" x2="6.01" y2="6"/><line x1="6" y1="18" x2="6.01" y2="18"/>'},{title:'Development Environment Setup',desc:'We configure local, staging, testing, and production-ready environments.',icon:'<circle cx="12" cy="12" r="3"/><path d="M19.07 4.93l-1.41 1.41M4.93 4.93l1.41 1.41"/>'},{title:'Database and Integration Planning',desc:'We structure product, customer, order, inventory, and integration data.',icon:'<ellipse cx="12" cy="5" rx="9" ry="3"/><path d="M21 12c0 1.66-4 3-9 3s-9-1.34-9-3"/><path d="M3 5v14c0 1.66 4 3 9 3s9-1.34 9-3V5"/>'},{title:'Project and Sprint Planning',desc:'We define tasks, milestones, reviews, responsibilities, and delivery schedules.',icon:'<polyline points="16 18 22 12 16 6"/><polyline points="8 6 2 12 8 18"/>'}],deliverables:['Technical architecture plan','Configured development environments','Database and API structure','Sprint schedule and coding standards'],illus:'<img src="Workflow Image/custom-web-development-project-planning-technical-setup.webp" alt="Platform Planning & Technical Setup" style="width:100%;height:auto;display:block;border:none;outline:none;border-radius:0;box-shadow:none;mix-blend-mode:multiply;filter:contrast(1.05) saturate(1.1);background:transparent;">' },
    {num:'03',label:'UI/UX & eCommerce Development',title:'UI/UX & eCommerce Development',desc:'Our designers and developers transform approved plans into a responsive, functional online store. Storefront interfaces, product features, administrative controls, checkout processes, databases, and integrations are developed around your customers and operations.',subs:[{title:'Responsive Storefront Development',desc:'We build responsive interfaces across desktops, tablets, and smartphones.',icon:'<rect x="3" y="3" width="7" height="7"/><rect x="14" y="3" width="7" height="7"/><rect x="3" y="14" width="7" height="7"/><rect x="14" y="14" width="7" height="7"/>'},{title:'Commerce Back-End Development',desc:'We develop catalogue, customer, order, pricing, and administrative functions.',icon:'<path d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z"/>'},{title:'Cart and Checkout Development',desc:'We create clear carts, checkout flows, payments, and confirmations.',icon:'<path d="M6 2L3 6v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V6l-3-4z"/><line x1="3" y1="6" x2="21" y2="6"/><path d="M16 10a4 4 0 0 1-8 0"/>'},{title:'API and Third-Party Integrations',desc:'We connect payments, shipping, CRM, ERP, and marketing platforms.',icon:'<circle cx="12" cy="12" r="3"/><circle cx="12" cy="12" r="9"/>'}],deliverables:['Responsive eCommerce storefront','Functional commerce back end','Cart, checkout, and payment workflows','Required APIs and third-party integrations'],illus:'<img src="Workflow Image/custom-web-development-backend-api-development.webp" alt="UI/UX & eCommerce Development" style="width:100%;height:auto;display:block;border:none;outline:none;border-radius:0;box-shadow:none;mix-blend-mode:multiply;filter:contrast(1.05) saturate(1.1);background:transparent;">' },
    {num:'04',label:'Testing, Security & Performance Optimization',title:'Testing, Security & Performance Optimization',desc:'Before launch, we test store functionality, transactions, integrations, security, compatibility, and performance. Identified issues are resolved and retested to provide a dependable shopping and administrative experience across supported devices and scenarios.',subs:[{title:'Functional and Transaction Testing',desc:'We test products, accounts, carts, payments, orders, and returns.',icon:'<polyline points="9 11 12 14 22 4"/><path d="M21 12v7a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11"/>'},{title:'Cross-Browser and Device Testing',desc:'We verify consistent behaviour across browsers, devices, and screens.',icon:'<line x1="18" y1="20" x2="18" y2="10"/><line x1="12" y1="20" x2="12" y2="4"/><line x1="6" y1="20" x2="6" y2="14"/>'},{title:'Performance Optimization',desc:'We optimize media, code, caching, databases, and loading performance.',icon:'<circle cx="12" cy="12" r="10"/><path d="M2 12h20M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10"/>'},{title:'Security and Payment Testing',desc:'We review authentication, permissions, transactions, data handling, and vulnerabilities.',icon:'<path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/>'}],deliverables:['Functional quality-assurance report','Payment and integration validation','Performance and compatibility results','Security review and resolved issues'],illus:'<img src="Workflow Image/custom-web-development-testing-performance-optimization.webp" alt="Testing, Security & Performance Optimization" style="width:100%;height:auto;display:block;border:none;outline:none;border-radius:0;box-shadow:none;mix-blend-mode:multiply;filter:contrast(1.05) saturate(1.1);background:transparent;">' },
    {num:'05',label:'Deployment & Store Launch',title:'Deployment & Store Launch',desc:'Following approval, we deploy the store to its production environment and complete hosting, domain, security, payment, analytics, backup, and monitoring configurations. Final checks confirm readiness for live customers and transactions.',subs:[{title:'Production Deployment',desc:'We deploy the approved store safely to production infrastructure.',icon:'<path d="M12 2L2 7l10 5 10-5-10-5z"/><path d="M2 17l10 5 10-5"/><path d="M2 12l10 5 10-5"/>'},{title:'Domain, Hosting and SSL Setup',desc:'We configure hosting, domains, DNS, SSL, and required services.',icon:'<path d="M17.5 19H9a7 7 0 1 1 6.71-9h1.79a4.5 4.5 0 1 1 0 9Z"/>'},{title:'Payments and Integrations Activation',desc:'We activate live payments, shipping, analytics, and connected systems.',icon:'<rect x="1" y="4" width="22" height="16" rx="2" ry="2"/><line x1="1" y1="10" x2="23" y2="10"/>'},{title:'Monitoring and Launch Validation',desc:'We monitor transactions, errors, performance, and critical store functions.',icon:'<rect x="3" y="11" width="18" height="11" rx="2" ry="2"/><path d="M7 11V7a5 5 0 0 1 10 0v4"/>'}],deliverables:['Fully launched online store','Domain, hosting, and security configuration','Live payment and integration setup','Launch checklist and monitoring configuration'],illus:'<img src="Workflow Image/custom-web-development-deployment-launch.webp" alt="Deployment & Store Launch" style="width:100%;height:auto;display:block;border:none;outline:none;border-radius:0;box-shadow:none;mix-blend-mode:multiply;filter:contrast(1.05) saturate(1.1);background:transparent;">' },
    {num:'06',label:'Maintenance & Continuous Improvement',title:'Maintenance & Continuous Improvement',desc:'Our support can continue after launch through updates, monitoring, troubleshooting, backups, performance improvement, and feature enhancements. This keeps the store reliable, secure, competitive, and prepared for changing business requirements.',subs:[{title:'Security and Platform Updates',desc:'We update platforms, extensions, libraries, and security configurations regularly.',icon:'<polyline points="1 4 1 10 7 10"/><polyline points="23 20 23 14 17 14"/><path d="M20.49 9A9 9 0 0 0 5.64 5.64L1 10m22 4l-4.64 4.36A9 9 0 0 1 3.51 15"/>'},{title:'Bug Fixes and Technical Support',desc:'We resolve store, payment, display, integration, and workflow issues.',icon:'<circle cx="12" cy="12" r="10"/><line x1="12" y1="8" x2="12" y2="16"/><line x1="8" y1="12" x2="16" y2="12"/>'},{title:'Performance and Conversion Monitoring',desc:'We monitor speed, availability, errors, transactions, and conversion behaviour.',icon:'<line x1="18" y1="20" x2="18" y2="10"/><line x1="12" y1="20" x2="12" y2="4"/><line x1="6" y1="20" x2="6" y2="14"/>'},{title:'Feature and Integration Enhancements',desc:'We add products, features, markets, channels, and business integrations.',icon:'<path d="M12 22v-4M12 2v4M4.93 4.93l2.83 2.83M16.24 16.24l2.83 2.83"/>'}],deliverables:['Regular store and security updates','Technical support and issue resolution','Performance and conversion monitoring','Feature enhancements and maintenance reports'],illus:'<img src="Workflow Image/custom-web-development-maintenance-continuous-improvement.webp" alt="Maintenance & Continuous Improvement" style="width:100%;height:auto;display:block;border:none;outline:none;border-radius:0;box-shadow:none;mix-blend-mode:multiply;filter:contrast(1.05) saturate(1.1);background:transparent;">' }
  ];`;

const stepsRegex = /const steps=\[\s*\{num:'01'[\s\S]*?\n  \];/;
if (stepsRegex.test(html)) {
  html = html.replace(stepsRegex, newStepsCode.trim());
  console.log('Successfully replaced steps array in indexecom1.html');
} else {
  console.error('Could not match steps array regex in indexecom1.html!');
}

fs.writeFileSync(filePath, html, 'utf8');
console.log('Successfully updated indexecom1.html with eCommerce DOCX workflow content');
