const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, 'index1.html');
let html = fs.readFileSync(filePath, 'utf8');

// 1. Replace steps array in JS
const newStepsCode = `  const steps=[
    {num:'01',label:'Requirements & Architecture Analysis',title:'Requirements & Architecture Analysis',desc:'We begin by understanding your business processes, users, application functions, data requirements, integrations, security expectations, and projected growth. This information helps us define an appropriate backend structure and technology direction.',subs:[{title:'Business and System Analysis',desc:'We examine business processes, users, objectives, challenges, and application requirements.',icon:'<path d="M3 3h18v18H3zM3 9h18M9 21V9"/>'},{title:'Technical Requirement Gathering',desc:'We document functions, integrations, permissions, workloads, and performance expectations.',icon:'<path d="M9 11l3 3L22 4"/><path d="M21 12v7a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11"/>'},{title:'Data and Integration Planning',desc:'We identify data structures, sources, relationships, APIs, and connected systems.',icon:'<rect x="3" y="3" width="18" height="18" rx="2"/><path d="M3 9h18M9 21V9"/>'},{title:'Technology Stack Selection',desc:'We select suitable languages, frameworks, databases, cloud, and security tools.',icon:'<path d="M12 2l3.09 6.26L22 9.27l-5 4.87L18.18 21 12 17.77 5.82 21 7 14.14l-5-4.87 6.91-1.01L12 2z"/>'}],deliverables:['Approved backend requirements document','Initial system architecture','Data and integration plan','Technology recommendation and project roadmap'],illus:'<img src="Workflow Image/custom-web-development-requirements-design-analysis.webp" alt="Requirements & Architecture Analysis" style="width:100%;height:auto;display:block;border:none;outline:none;border-radius:0;box-shadow:none;mix-blend-mode:multiply;filter:contrast(1.05) saturate(1.1);background:transparent;">' },
    {num:'02',label:'Project Planning & Technical Setup',title:'Project Planning & Technical Setup',desc:'Once requirements are approved, we establish the development plan, backend architecture, database design, environments, standards, and delivery milestones. This creates an organised technical foundation for efficient development and collaboration.',subs:[{title:'Backend Architecture',desc:'We define modules, services, communication methods, security, and system dependencies.',icon:'<rect x="2" y="2" width="20" height="8" rx="2"/><rect x="2" y="14" width="20" height="8" rx="2"/><line x1="6" y1="6" x2="6.01" y2="6"/><line x1="6" y1="18" x2="6.01" y2="18"/>'},{title:'Database Design',desc:'We structure tables, collections, relationships, indexes, and data-access requirements.',icon:'<ellipse cx="12" cy="5" rx="9" ry="3"/><path d="M21 12c0 1.66-4 3-9 3s-9-1.34-9-3"/><path d="M3 5v14c0 1.66 4 3 9 3s9-1.34 9-3V5"/>'},{title:'Development Environment Setup',desc:'We configure local, staging, testing, and production-ready backend environments.',icon:'<circle cx="12" cy="12" r="3"/><path d="M19.07 4.93l-1.41 1.41M4.93 4.93l1.41 1.41"/>'},{title:'Sprint and Coding Standards',desc:'We establish milestones, coding conventions, reviews, documentation, and version control.',icon:'<polyline points="16 18 22 12 16 6"/><polyline points="8 6 2 12 8 18"/>'}],deliverables:['Detailed backend architecture','Database design and data models','Configured development environments','Sprint schedule and coding standards'],illus:'<img src="Workflow Image/custom-web-development-project-planning-technical-setup.webp" alt="Project Planning & Technical Setup" style="width:100%;height:auto;display:block;border:none;outline:none;border-radius:0;box-shadow:none;mix-blend-mode:multiply;filter:contrast(1.05) saturate(1.1);background:transparent;">' },
    {num:'03',label:'Backend & API Development',title:'Backend & API Development',desc:'Our developers transform the approved architecture into functional server-side systems, databases, APIs, authentication, and business logic. Every component is developed according to documented operational and technical requirements.',subs:[{title:'Server-Side Development',desc:'We build application logic, workflows, background processes, and administrative functions.',icon:'<path d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z"/>'},{title:'API Development',desc:'We create secure APIs connecting interfaces, platforms, and third-party services.',icon:'<circle cx="12" cy="12" r="3"/><circle cx="12" cy="12" r="9"/>'},{title:'Database Implementation',desc:'We develop schemas, queries, indexes, validation, caching, and backups.',icon:'<ellipse cx="12" cy="5" rx="9" ry="3"/><path d="M21 12c0 1.66-4 3-9 3s-9-1.34-9-3"/><path d="M3 5v14c0 1.66 4 3 9 3s9-1.34 9-3V5"/>'},{title:'Security and Authentication',desc:'We implement access controls, authentication, encryption, and secure data handling.',icon:'<path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/>'}],deliverables:['Functional backend application','Secure API endpoints','Implemented database system','Authentication and access-control modules'],illus:'<img src="Workflow Image/custom-web-development-backend-api-development.webp" alt="Backend & API Development" style="width:100%;height:auto;display:block;border:none;outline:none;border-radius:0;box-shadow:none;mix-blend-mode:multiply;filter:contrast(1.05) saturate(1.1);background:transparent;">' },
    {num:'04',label:'Testing, Security & Optimization',title:'Testing, Security & Optimization',desc:'Before deployment, we test functionality, APIs, databases, integrations, security controls, and application performance. Identified issues are documented, corrected, and retested under realistic operating conditions.',subs:[{title:'Functional and API Testing',desc:'We verify endpoints, workflows, validations, errors, permissions, and expected responses.',icon:'<polyline points="9 11 12 14 22 4"/><path d="M21 12v7a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11"/>'},{title:'Security Testing',desc:'We review authentication, encryption, vulnerabilities, access controls, and configurations.',icon:'<path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/>'},{title:'Performance and Load Testing',desc:'We measure response times, concurrency, resource usage, and scaling behaviour.',icon:'<line x1="18" y1="20" x2="18" y2="10"/><line x1="12" y1="20" x2="12" y2="4"/><line x1="6" y1="20" x2="6" y2="14"/>'},{title:'Integration and Data Validation',desc:'We confirm accurate data exchange across all connected systems and services.',icon:'<circle cx="12" cy="12" r="10"/><path d="M2 12h20M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10"/>'}],deliverables:['Functional and API testing report','Security assessment and resolved issues','Performance and load-testing results','Integration and data-validation approval'],illus:'<img src="Workflow Image/custom-web-development-testing-performance-optimization.webp" alt="Testing, Security & Optimization" style="width:100%;height:auto;display:block;border:none;outline:none;border-radius:0;box-shadow:none;mix-blend-mode:multiply;filter:contrast(1.05) saturate(1.1);background:transparent;">' },
    {num:'05',label:'Deployment & CI/CD Launch',title:'Deployment & CI/CD Launch',desc:'After quality approval, we deploy the backend to its production environment and configure automation, infrastructure, monitoring, security, and recovery systems for a controlled and dependable launch.',subs:[{title:'Production Deployment',desc:'We deploy approved backend services safely into the production environment.',icon:'<path d="M12 2L2 7l10 5 10-5-10-5z"/><path d="M2 17l10 5 10-5"/><path d="M2 12l10 5 10-5"/>'},{title:'CI/CD Pipeline',desc:'We automate application builds, tests, approvals, deployments, and rollback processes.',icon:'<polyline points="22 12 18 12 15 21 9 3 6 12 2 12"/>'},{title:'Cloud and Server Configuration',desc:'We configure servers, cloud services, networking, permissions, and scaling policies.',icon:'<path d="M17.5 19H9a7 7 0 1 1 6.71-9h1.79a4.5 4.5 0 1 1 0 9Z"/>'},{title:'Monitoring and Backup Setup',desc:'We establish logs, alerts, health monitoring, backups, and recovery procedures.',icon:'<rect x="3" y="11" width="18" height="11" rx="2" ry="2"/><path d="M7 11V7a5 5 0 0 1 10 0v4"/>'}],deliverables:['Production-ready backend system','Configured CI/CD pipeline','Cloud and server setup','Monitoring, backup, and recovery configuration'],illus:'<img src="Workflow Image/custom-web-development-deployment-launch.webp" alt="Deployment & CI/CD Launch" style="width:100%;height:auto;display:block;border:none;outline:none;border-radius:0;box-shadow:none;mix-blend-mode:multiply;filter:contrast(1.05) saturate(1.1);background:transparent;">' },
    {num:'06',label:'Maintenance & Continuous Improvement',title:'Maintenance & Continuous Improvement',desc:'Our support continues after deployment through monitoring, security updates, database maintenance, troubleshooting, optimization, and feature enhancements. This keeps the backend reliable and prepared for evolving requirements.',subs:[{title:'Security and Dependency Updates',desc:'We update frameworks, libraries, services, configurations, and security controls.',icon:'<polyline points="1 4 1 10 7 10"/><polyline points="23 20 23 14 17 14"/><path d="M20.49 9A9 9 0 0 0 5.64 5.64L1 10m22 4l-4.64 4.36A9 9 0 0 1 3.51 15"/>'},{title:'Monitoring and Incident Support',desc:'We monitor system health and respond to operational issues promptly.',icon:'<circle cx="12" cy="12" r="10"/><line x1="12" y1="8" x2="12" y2="16"/><line x1="8" y1="12" x2="16" y2="12"/>'},{title:'Database Maintenance',desc:'We optimise queries, storage, indexes, backups, and database performance.',icon:'<line x1="18" y1="20" x2="18" y2="10"/><line x1="12" y1="8" x2="12" y2="4"/><line x1="6" y1="20" x2="6" y2="14"/>'},{title:'Feature and Scalability Enhancements',desc:'We add functions, integrations, resources, and architectural improvements when required.',icon:'<path d="M12 22v-4M12 2v4M4.93 4.93l2.83 2.83M16.24 16.24l2.83 2.83"/>'}],deliverables:['Security and software updates','Monitoring and technical support','Database and performance maintenance','Feature enhancements and maintenance reports'],illus:'<img src="Workflow Image/custom-web-development-maintenance-continuous-improvement.webp" alt="Maintenance & Continuous Improvement" style="width:100%;height:auto;display:block;border:none;outline:none;border-radius:0;box-shadow:none;mix-blend-mode:multiply;filter:contrast(1.05) saturate(1.1);background:transparent;">' }
  ];`;

const stepsRegex = /const steps=\[\s*\{num:'01'[\s\S]*?\n  \];/;
if (stepsRegex.test(html)) {
  html = html.replace(stepsRegex, newStepsCode.trim());
  console.log('Successfully replaced steps array in index1.html');
} else {
  console.error('Could not match steps array regex!');
}

// 2. Enhance CSS for Tech Stack icons spacing
const oldGridCSS = '.ts-tech-grid{display:flex;align-items:center;gap:8px;overflow-x:auto;scrollbar-width:none;-ms-overflow-style:none;flex-wrap:nowrap}';
const newGridCSS = '.ts-tech-grid{display:flex;align-items:flex-start;gap:16px 20px;overflow-x:auto;scrollbar-width:none;-ms-overflow-style:none;flex-wrap:wrap;padding:4px 0}';

const oldItemCSS = '.ts-tech-item{display:flex;flex-direction:column;align-items:center;gap:5px;text-align:center;cursor:default;flex-shrink:0;width:72px}';
const newItemCSS = '.ts-tech-item{display:flex;flex-direction:column;align-items:center;gap:6px;text-align:center;cursor:default;flex-shrink:0;min-width:88px;max-width:105px;width:auto;padding:10px 8px;border-radius:12px;background:rgba(255,255,255,.03);border:1px solid rgba(255,255,255,.06);transition:all .25s ease}';

const oldItemImgCSS = '.ts-tech-item img{width:36px;height:36px;object-fit:contain;flex-shrink:0;animation:tsTechFloat 3s ease-in-out infinite}';
const newItemImgCSS = '.ts-tech-item img{width:42px;height:42px;object-fit:contain;flex-shrink:0;margin-bottom:4px;animation:tsTechFloat 3s ease-in-out infinite}.ts-tech-item svg{width:38px;height:38px;flex-shrink:0;margin-bottom:4px}';

const oldSpanCSS = '.ts-tech-item span{font-size:12px;color:#101828;font-weight:600;white-space:nowrap}';
const newSpanCSS = '.ts-tech-item span{font-size:11.5px;color:#101828;font-weight:600;white-space:normal;word-wrap:break-word;line-height:1.35;text-align:center}';

const oldCardCSS = '.ts-card{flex:1;background:rgba(255,255,255,.04);border:1px solid rgba(255,255,255,.09);border-radius:14px;padding:16px 22px;backdrop-filter:blur(8px);min-width:0;overflow:hidden}';
const newCardCSS = '.ts-card{flex:1;background:rgba(255,255,255,.04);border:1px solid rgba(255,255,255,.09);border-radius:16px;padding:20px 24px;backdrop-filter:blur(8px);min-width:0;overflow:visible}';

if (html.includes(oldGridCSS)) html = html.replace(oldGridCSS, newGridCSS);
if (html.includes(oldItemCSS)) html = html.replace(oldItemCSS, newItemCSS);
if (html.includes(oldItemImgCSS)) html = html.replace(oldItemImgCSS, newItemImgCSS);
if (html.includes(oldSpanCSS)) html = html.replace(oldSpanCSS, newSpanCSS);
if (html.includes(oldCardCSS)) html = html.replace(oldCardCSS, newCardCSS);

// Light mode overrides
const oldLightItemOverride = '.ts-header p,.ts-tech-item span{color:#101828!important}';
const newLightItemOverride = '.ts-header p,.ts-tech-item span{color:#101828!important}.ts-tech-item{background:#f8fafc!important;border:1px solid rgba(139,92,246,.12)!important;box-shadow:0 2px 8px rgba(7,22,79,.03)!important}.ts-tech-item:hover{background:#ffffff!important;border-color:rgba(139,92,246,.35)!important;box-shadow:0 8px 20px rgba(139,92,246,.15)!important;transform:translateY(-4px)!important}';

if (html.includes(oldLightItemOverride)) html = html.replace(oldLightItemOverride, newLightItemOverride);

fs.writeFileSync(filePath, html, 'utf8');
console.log('Successfully updated index1.html with HWW section from DOCX and spacious Tech Stack styling');
